create table if not exists users (
    id bigint generated by default as identity primary key,
    active boolean not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null unique
);

create table if not exists training_types (
    id bigint generated by default as identity primary key,
    training_type_name varchar(255) not null unique
);

create table if not exists trainees (
    id bigint generated by default as identity primary key,
    address varchar(255),
    date_of_birth date,
    user_id bigint not null unique,
    constraint fk_trainees_user foreign key (user_id) references users (id)
);

create table if not exists trainers (
    id bigint generated by default as identity primary key,
    specialization_id bigint not null,
    user_id bigint not null unique,
    constraint fk_trainers_specialization foreign key (specialization_id) references training_types (id),
    constraint fk_trainers_user foreign key (user_id) references users (id)
);

create table if not exists trainings (
    id bigint generated by default as identity primary key,
    trainee_id bigint not null,
    trainer_id bigint not null,
    training_date date not null,
    training_duration integer not null,
    training_name varchar(255) not null,
    training_type_id bigint not null,
    constraint fk_trainings_trainee foreign key (trainee_id) references trainees (id) on delete cascade,
    constraint fk_trainings_trainer foreign key (trainer_id) references trainers (id),
    constraint fk_trainings_type foreign key (training_type_id) references training_types (id)
);

create table if not exists trainees_trainers (
    trainee_id bigint not null,
    trainer_id bigint not null,
    primary key (trainee_id, trainer_id),
    constraint fk_trainees_trainers_trainee foreign key (trainee_id) references trainees (id) on delete cascade,
    constraint fk_trainees_trainers_trainer foreign key (trainer_id) references trainers (id) on delete cascade
);

create index if not exists idx_trainees_user_id on trainees (user_id);
create index if not exists idx_trainers_user_id on trainers (user_id);
create index if not exists idx_trainers_specialization_id on trainers (specialization_id);
create index if not exists idx_trainings_trainee_id on trainings (trainee_id);
create index if not exists idx_trainings_trainer_id on trainings (trainer_id);
create index if not exists idx_trainings_type_id on trainings (training_type_id);
create index if not exists idx_trainings_training_date on trainings (training_date);
