create table if not exists users (
    id bigint generated by default as identity primary key,
    active boolean not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    username varchar(255) not null unique
);

create table if not exists training_type (
    id bigint generated by default as identity primary key,
    training_type_name varchar(255) not null unique
);

create table if not exists trainee (
    id bigint generated by default as identity primary key,
    address varchar(255),
    date_of_birth date,
    user_id bigint not null unique,
    constraint fk_trainee_user foreign key (user_id) references users (id)
);

create table if not exists trainer (
    id bigint generated by default as identity primary key,
    specialization_id bigint not null,
    user_id bigint not null unique,
    constraint fk_trainer_specialization foreign key (specialization_id) references training_type (id),
    constraint fk_trainer_user foreign key (user_id) references users (id)
);

create table if not exists training (
    id bigint generated by default as identity primary key,
    trainee_id bigint not null,
    trainer_id bigint not null,
    training_date date not null,
    training_duration integer not null,
    training_name varchar(255) not null,
    training_type_id bigint not null,
    constraint fk_training_trainee foreign key (trainee_id) references trainee (id),
    constraint fk_training_trainer foreign key (trainer_id) references trainer (id),
    constraint fk_training_type foreign key (training_type_id) references training_type (id)
);

create table if not exists trainee_trainer (
    trainee_id bigint not null,
    trainer_id bigint not null,
    primary key (trainee_id, trainer_id),
    constraint fk_trainee_trainer_trainee foreign key (trainee_id) references trainee (id),
    constraint fk_trainee_trainer_trainer foreign key (trainer_id) references trainer (id)
);

create index if not exists idx_trainee_user_id on trainee (user_id);
create index if not exists idx_trainer_user_id on trainer (user_id);
create index if not exists idx_trainer_specialization_id on trainer (specialization_id);
create index if not exists idx_training_trainee_id on training (trainee_id);
create index if not exists idx_training_trainer_id on training (trainer_id);
create index if not exists idx_training_type_id on training (training_type_id);
create index if not exists idx_training_training_date on training (training_date);
