spring.application.name=gym-crm
spring.profiles.default=prod
spring.mvc.servlet.path=/api
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus

password.length=10
password.alphabet=ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
lombok.addLombokGeneratedAnnotation=true
