CREATE TABLE trainer_workloads (
                                   username VARCHAR(100) PRIMARY KEY,
                                   first_name VARCHAR(100) NOT NULL,
                                   last_name VARCHAR(100) NOT NULL,
                                   active BOOLEAN NOT NULL
);

CREATE TABLE trainer_monthly_summaries (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           trainer_username VARCHAR(100) NOT NULL,
                                           training_year INTEGER NOT NULL,
                                           training_month INTEGER NOT NULL,
                                           summary_duration INTEGER NOT NULL,
                                           CONSTRAINT fk_trainer_monthly_summaries_trainer
                                               FOREIGN KEY (trainer_username)
                                                   REFERENCES trainer_workloads(username)
                                                   ON DELETE CASCADE,
                                           CONSTRAINT uk_trainer_monthly_summaries_period
                                               UNIQUE (trainer_username, training_year, training_month),
                                           CONSTRAINT ck_trainer_monthly_summaries_duration
                                               CHECK (summary_duration >= 0)
);
