CREATE TABLE trainer_workload_processed_events (
                                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   training_id BIGINT NOT NULL,
                                                   action_type VARCHAR(20) NOT NULL,
                                                   processed_at TIMESTAMP NOT NULL,
                                                   CONSTRAINT uk_trainer_workload_processed_events_training_action
                                                       UNIQUE (training_id, action_type)
);
