verify:trainer-workload:
  stage: verify
  services:
    - name: docker:24.0.9-dind
      command: ["--tls=false"]
  script:
    - mvn $MAVEN_CLI_OPTS -f trainer-workload/pom.xml verify
  artifacts:
    when: always
    reports:
      junit: trainer-workload/target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: trainer-workload/target/site/jacoco/jacoco.xml
    paths:
      - trainer-workload/target/site/jacoco/
      - trainer-workload/target/surefire-reports/
    expire_in: 1 week
  rules:
    - changes:
        - trainer-workload/**/*
        - .gitlab-ci.yml
        - trainer-workload/.gitlab-ci.yml
