CREATE TABLE trainer_workload_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_id BIGINT NOT NULL,
    trainer_username VARCHAR(100) NOT NULL,
    trainer_first_name VARCHAR(100) NOT NULL,
    trainer_last_name VARCHAR(100) NOT NULL,
    trainer_status BOOLEAN NOT NULL,
    training_date DATE NOT NULL,
    training_duration INTEGER NOT NULL,
    action_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    retry_count INTEGER NOT NULL,
    next_retry_at TIMESTAMP WITH TIME ZONE NOT NULL,
    error_message VARCHAR(1000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_trainer_workload_outbox_training_duration
        CHECK (training_duration > 0),
    CONSTRAINT ck_trainer_workload_outbox_retry_count
        CHECK (retry_count >= 0),
    CONSTRAINT ck_trainer_workload_outbox_action_type
        CHECK (action_type IN ('ADD', 'DELETE')),
    CONSTRAINT ck_trainer_workload_outbox_status
        CHECK (status IN ('PENDING', 'SENT'))
);

CREATE INDEX idx_trainer_workload_outbox_pending
    ON trainer_workload_outbox (status, next_retry_at, created_at);
